### ISSUE TITLE
wood texture showing as black now

### ISSUE THREAD

**Issue by owntheweb-archive** [bitgridio/space-foundation#1]
I'm seeing this issue now as well, after I upgraded to the latest janusvr. What once looked like a wood texture is now black. I'll check it out soon, along with the new video loop that was loaded.

**Comment by sirkitree** [comment]
Oh good, I'm not crazy.

The material file looks okay: https://github.com/bitgridio/space-foundation/blob/gh-pages/assets/images/__Wood_Cherry_Original_4.jpg

And the model is pointing to this file as well: https://github.com/bitgridio/space-foundation/blob/gh-pages/assets/models/482-amphitheatre_0.dae#L1823

So I'm not sure what's up.

**Comment by owntheweb-archive** [comment]
Initial gut feeling: image is corrupt somehow or in some partially unsupported format (e.g. not sure how janusvr supports progressive jpgs). I'll re-export the jpg and relink to see what happens later as time allows.

**Comment by owntheweb-archive** [comment]
going to close this as no longer relevant :D
